aloitusluento.pdf: aloitusluento.md
	pandoc -t beamer -V colortheme=crane aloitusluento.md -o aloitusluento.pdf

lecture.pdf: lecture.md
	pandoc -t beamer -V colortheme=crane lecture.md -o lecture.pdf